### ISSUE TITLE
The dark mode toggle button could be better placed

### ISSUE THREAD

**Issue by AdityaPrakash-26** [ComputerScientist-01/portfolio-repository#3]
It seems very weird having the toggle button right in the middle of nowhere. Maybe place it on the top right or create a navbar for it?

**Comment by ComputerScientist-01** [comment]
seems about right could i assign this issue to you ?

**Comment by AdityaPrakash-26** [comment]
I have linked a pull request that solves this issue. @ComputerScientist-01
